name: Build Test
on:
  push:
    branches: [ "master" ]
    paths:
      - "src/**"
      - "package.json"
      - "nest-cli.app.json"
      - "nest-cli.cli.json"
      - "tsconfig.json"
      - "tsconfig.build.json"
    

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Dependencies
      run: npm install --production

    - name: Build Web
      run: |
        npm run build:app

    - name: Build Cli Command
      run: |
        npm run build:cli
